name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Production
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        # deployment script here
        # Example using SSH
        # ssh user@your-server "cd /path/to/app && git pull && npm install && npm run build"
